=== salifbiaye/whatsup2/storage/dtd/groups.dtd
<!ELEMENT groups (group*)>
<!ELEMENT group (name, admin, members, messages)>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT admin (#PCDATA)>
<!ELEMENT members (member*)>
<!ELEMENT member (#PCDATA)>
<!ELEMENT messages (message*)>
<!ELEMENT message (text)>
<!ATTLIST message id ID #REQUIRED sender IDREF #REQUIRED timestamp CDATA #REQUIRED>
<!ELEMENT text (#PCDATA)>
<!ATTLIST message encrypted CDATA #REQUIRED>

=== salifbiaye/whatsup2/storage/xml/groups.xml
<?xml version="1.0"?>
<!DOCTYPE groups SYSTEM "../dtd/groups.dtd">
<groups>
<group id="g1"><name>loro jacksoon</name><admin>u2</admin><created_at>2025-07-15T20:24:45+00:00</created_at><members><member>u1</member><member>u2</member></members><messages></messages></group></groups>
