=== salifbiaye/whatsup2/storage/dtd/users.dtd
<!ELEMENT users (user*)>
<!ELEMENT user (email, password, displayName, avatar, status, contacts)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT displayName (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT contacts (contact*)>
<!ELEMENT contact (#PCDATA)>
<!ATTLIST user id ID #REQUIRED>

=== salifbiaye/whatsup2/storage/xml/users.xml
<?xml version="1.0"?>
<!DOCTYPE users SYSTEM "../dtd/users.dtd">
<users>
<user id="u1"><email>goldlif94@gmail.com</email><password>d515c93fa586820e829431093234420e</password><displayName>roger</displayName><avatar>storage/avatars/avatar_default.png</avatar><status>online</status><contacts><contact>u2</contact></contacts></user><user id="u2"><email>zal.diop@gmail.com</email><password>d515c93fa586820e829431093234420e</password><displayName>zal</displayName><avatar>storage/avatars/avatar_default.png</avatar><status>online</status><contacts><contact>u1</contact></contacts></user></users>
